2022.12.25

## Numpy
- numpy
- ndarray
- Handling shape
- Indexing
- Slicing
- Creation function
- Operation functions
- array operations
- Comparisons
- Boolean Index
- Fancy Index
- numpy data i/o

In [2]:
import numpy as np

test_array = np.array([1, 4, 5, 8], float) # floast으로 생성됨. 데이터 타입을 설정해서 생성가능
print(test_array)
type(test_array)

[1. 4. 5. 8.]


numpy.ndarray

In [4]:
test_array = np.array([1, 4, 5, "8"], float) #	String Type의 데이터를 입력해도
print(test_array)
print(type(test_array[3]))	 	 	 #	Float Type으로 자동 형변환을 실시
print(test_array.dtype)              #	Array(배열)	전체의 데이터 Type을 반환함
print(test_array.shape)              #	Array(배열)	의 shape을 반환함

[1. 4. 5. 8.]
<class 'numpy.float64'>
float64
(4,)


In [5]:
matrix  = [[1,2,5,8],[1,2,5,8],[1,2,5,8]]
np.array(matrix, int).shape

(3, 4)

In [6]:
tensor  = [[[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]], 
           [[1,2,5,8],[1,2,5,8],[1,2,5,8]]]
np.array(tensor, int).shape

(4, 3, 4)

In [8]:
np.array(tensor, int).ndim # 차원

48

In [9]:
np.array(tensor, int).size # 갯수

48

In [12]:
test_matrix = [[1,2,3,4], [1,2,5,8]] # 2,4 
np.array(test_matrix).shape

(2, 4)

In [13]:
np.array(test_matrix).reshape(2,2,2) # 2,2,2 로 변경

array([[[1, 2],
        [3, 4]],

       [[1, 2],
        [5, 8]]])

In [14]:
test =np.array(test_matrix).reshape(8,) #1,8로 변경
test

array([1, 2, 3, 4, 1, 2, 5, 8])

In [16]:
test.reshape(-1, 2) # -1은 size를 기반으로 row 개수를 선정해줌

array([[1, 2],
       [3, 4],
       [1, 2],
       [5, 8]])

In [17]:
# flatten : 다차원 array를 1차원 array로 변환
test_matrix = [[[1,2,3,4], [1,2,5,8]], [[1,2,3,4], [1,2,5,8]]]
np.array(test_matrix).flatten()

array([1, 2, 3, 4, 1, 2, 5, 8, 1, 2, 3, 4, 1, 2, 5, 8])

In [10]:
# nbytes – ndarray object의 메모리 크기를 반환함
np.array([[1, 2, 3], [4.5, "5", "6"]], dtype=np.float32).nbytes

24

In [18]:
# indexing
test_exmaple = np.array([[1, 2, 3], [4.5, 5, 6]], int)
test_exmaple

array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
test_exmaple[0,0] = 10 # Matrix 0,0 에 12 할당
test_exmaple

array([[10,  2,  3],
       [ 4,  5,  6]])

In [20]:
test_exmaple[0][0] = 5 # Matrix 0,0 에 12 할당
test_exmaple[0,0]

5

In [24]:
# slicing
test_exmaple = np.array([[1, 2, 5,8], [1, 2, 5,8],[1, 2, 5,8],[1, 2, 5,8]], int)
print(test_exmaple)
test_exmaple[:2,:] 

[[1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]
 [1 2 5 8]]


array([[1, 2, 5, 8],
       [1, 2, 5, 8]])

In [23]:
print(test_exmaple[:,1:3] ) # 열에서 2,3 번째부분을 전체를 빼냄
test_exmaple[1,:2]          

[[2 5]
 [2 5]
 [2 5]
 [2 5]]


array([1, 2])

In [26]:
a = np.arange(100).reshape(10,10)
print(a)
a[:, -1].reshape(-1,1)

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]


array([[ 9],
       [19],
       [29],
       [39],
       [49],
       [59],
       [69],
       [79],
       [89],
       [99]])

In [27]:
# create numpy
np.arange(30).reshape(-1,5) # size기준으로

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [28]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [30]:
np.arange(30).reshape(6,5) # 위의 -1,5와 동일

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

In [36]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [37]:
test_matrix = np.arange(30).reshape(5,6)
np.zeros_like(test_matrix)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [38]:
# identuty & digonal & eye
np.identity(n=3, dtype=np.int8) # identify 단위 행렬 생성

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [39]:
# eye
# 대각선인 1인 행렬, k값의 시작 index의 변경이 가능
np.eye(N=3, M=5, dtype=np.int8)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0]], dtype=int8)

In [40]:
np.eye(3,5,k=2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
# diag
# 대각 행렬의 값을 추출함
matrix = np.arange(9).reshape(3,3)
np.diag(matrix)

array([0, 4, 8])

In [3]:
# operation
test_array = np.arange(1,13).reshape(3,4)
print(test_array)
test_array.sum()

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


78

In [4]:
test_array.sum(axis=1)

array([10, 26, 42])

In [5]:
test_array.sum(axis=0)

array([15, 18, 21, 24])

In [6]:
third_order_tensor = np.array([test_array,test_array,test_array])
third_order_tensor

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [7]:
third_order_tensor.sum(axis=2)

array([[10, 26, 42],
       [10, 26, 42],
       [10, 26, 42]])

In [8]:
third_order_tensor.sum(axis=1)

array([[15, 18, 21, 24],
       [15, 18, 21, 24],
       [15, 18, 21, 24]])

In [9]:
third_order_tensor.sum(axis=0)

array([[ 3,  6,  9, 12],
       [15, 18, 21, 24],
       [27, 30, 33, 36]])

In [11]:
# concatenate
a = np.array([1, 2, 3])
b = np.array([2, 3, 4])
np.vstack((a,b))

array([[1, 2, 3],
       [2, 3, 4]])

In [13]:
a = np.array([ [1], [2], [3]])
b = np.array([ [2], [3], [4]])
np.hstack((a,b))

array([[1, 2],
       [2, 3],
       [3, 4]])

In [14]:
a = np.array([[1, 2, 3]])
b = np.array([[2, 3, 4]])
np.concatenate( (a,b) ,axis=0)

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

np.concatenate( (a,b.T) ,axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [16]:
# tolist : 같은 위치에 있는 데이터끼리 묶어줌
a.tolist()

[[1, 2], [3, 4]]

In [19]:
# dot product
test_a = np.arange(1,7).reshape(2,3)
test_b = np.arange(7,13).reshape(3,2)
print(test_a)
print(test_b)
test_a.dot(test_b)

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]


array([[ 58,  64],
       [139, 154]])

In [20]:
test_a.transpose() 

array([[1, 4],
       [2, 5],
       [3, 6]])

In [21]:
test_a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [22]:
test_a.T.dot(test_a) # Matrix 간 곱셈

array([[17, 22, 27],
       [22, 29, 36],
       [27, 36, 45]])

In [24]:
test_matrix = np.array([[1,2,3],[4,5,6]], float)
scalar = 3
test_matrix

array([[1., 2., 3.],
       [4., 5., 6.]])

In [25]:
test_matrix + scalar # Matrix - Scalar 덧셈

array([[4., 5., 6.],
       [7., 8., 9.]])

In [26]:
test_matrix * 5 # Matrix - Scalar 곱셈

array([[ 5., 10., 15.],
       [20., 25., 30.]])

In [28]:
test_matrix = np.arange(1,13).reshape(4,3)
test_vector = np.arange(10,40,10)
print(test_matrix)
print(test_vector)
test_matrix+ test_vector

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[10 20 30]


array([[11, 22, 33],
       [14, 25, 36],
       [17, 28, 39],
       [20, 31, 42]])

In [3]:
# all & any
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
a>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [5]:
# 하나라도 만족하면 True 
np.any(a>5), np.any(a<0)

(True, False)

In [6]:
# 모두 만족해야 True
np.all(a>5) , np.all(a < 10)

(False, True)

In [7]:
# comparision operation
test_a = np.array([1, 3, 0], float)
test_b = np.array([5, 2, 1], float)
test_a > test_b 

array([False,  True, False])

In [8]:
test_a == test_b 

array([False, False, False])

In [9]:
# 하나라도 만족하기때문에 True가 나옴
(test_a > test_b).any()

True

In [10]:
# and, not, or도 사용가능
a = np.array([1, 3, 0], float)
np.logical_and(a > 0, a < 3) # and 조건의 condition

array([ True, False, False])

In [11]:
b = np.array([True, False, True], bool)
np.logical_not(b) # NOT 조건의 condition

array([False,  True, False])

In [12]:
c = np.array([False, True, False], bool)
np.logical_or(b, c) # OR 조건의 condition

array([ True,  True,  True])

In [14]:
# where
print(a)
np.where(a > 0, 3, 2) 
# 각 자리에 1과 0 / 3과 3 /0과 2를 비교하여 맞으면 True면 3 False면 2를 출력


[1. 3. 0.]


array([3, 3, 2])

In [15]:
# index값을 반환함
# 현재 3,3,2 에서 0보다 크면 0반환하고 그다음이 0보다 크기때문에 1 그다음은 반환이 되지않음.
np.where(a>0)

(array([0, 1]),)

In [16]:
a = np.arange(5, 15)
a

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
# 인덱스의 위치값을 반환해줌
np.where(a>10)

(array([6, 7, 8, 9]),)

In [18]:
# nan이 있는지 없는지 물어보는 함수
a = np.array([1, np.NaN, np.Inf], float)
np.isnan(a)

array([False,  True, False])

In [19]:
# finite number가 있는지 없는지 물어보는 함수
np.isfinite(a)

array([ True, False, False])

In [21]:
# argmax & argmin 최대 최소 값
np.argmax(a) , np.argmin(a)

(1, 1)

In [23]:
# 위치의 인덱스 번호가 찍힘.
a=np.array([[1,2,4,7],[9,88,6,45],[9,76,3,4]])
print(a)
np.argmax(a, axis=1) , np.argmin(a, axis=0)


[[ 1  2  4  7]
 [ 9 88  6 45]
 [ 9 76  3  4]]


(array([3, 1, 1]), array([0, 0, 2, 2]))

In [24]:
# bool index
test_array = np.array([1, 4, 0, 2, 3, 8, 9, 7], float)
test_array > 3

array([False,  True, False, False, False,  True,  True,  True])

In [26]:
# 조건이 Ture인 index의 element만 추출
test_array[test_array > 3]

array([4., 8., 9., 7.])

In [25]:

condition = test_array < 3 
test_array[condition]

array([1., 0., 2.])

In [27]:
# 
A = np.array([
[12, 13, 14, 12, 16, 14, 11, 10,  9],
[11, 14, 12, 15, 15, 16, 10, 12, 11],
[10, 12, 12, 15, 14, 16, 10, 12, 12],
[ 9, 11, 16, 15, 14, 16, 15, 12, 10],
[12, 11, 16, 14, 10, 12, 16, 12, 13],
[10, 15, 16, 14, 14, 14, 16, 15, 12],
[13, 17, 14, 10, 14, 11, 14, 15, 10],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 17, 19, 16, 17, 18, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 16, 12, 14, 11, 12, 14, 18, 11],
[10, 19, 12, 14, 11, 12, 14, 18, 10],
[14, 22, 12, 14, 11, 12, 14, 17, 13],
[10, 16, 12, 14, 11, 12, 14, 18, 11]])
# 조건 B값은 조건문에 의해 Ture or False로 나옴
# True는 1 False는 0
# 거기서 astype으로 추출하여 True와 False를 1과 0으로 출력
B = A < 15
B.astype(np.int)

<ipython-input-27-561b1af7b31a>:18: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  B.astype(np.int)


array([[1, 1, 1, 1, 0, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 0, 1, 1, 1],
       [1, 1, 1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 0, 1, 0, 0, 1, 1],
       [1, 1, 0, 1, 1, 1, 0, 1, 1],
       [1, 0, 0, 1, 1, 1, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1],
       [1, 0, 1, 1, 1, 1, 1, 0, 1]])

In [28]:
# fancy index

In [30]:
# 값을 뽑아줌
a = np.array([2, 4, 6, 8], float)
a[a>4] 

array([6., 8.])

In [32]:
a.take(b) #take 함수: bracket index와 같은 효과

array([1., 1., 4., 4., 1.])

In [31]:
a = np.array([[1, 4], [9, 16]], float)
b = np.array([0, 0, 1, 1, 0], int)
c = np.array([0, 1, 1, 1, 1], int)
a[b,c] # b를 row index, c를 column index로 변환하여 표시함
#     0  1
#  0  1  4
#  1  9  16
# 현재 배열의 매트릭스 상태를 의미
# b와 c를 보고 00은 1 01은 4 11은 16을 출력함

array([ 1.,  4., 16., 16.,  4.])